Disallow to delete main branch

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -23,7 +23,14 @@ PUSH_COMMAND=$(ps -ocommand= -p $PPID)
 
 IS_DESTRUCTIVE="\-\-delete|\-f"
 
+PROTECTED_BRANCH="trailblazer"
+CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+
 if [[ $PUSH_COMMAND =~ $IS_DESTRUCTIVE ]]; then
+    if [ $CURRENT_BRANCH = $PROTECTED_BRANCH ] || [[ $PUSH_COMMAND =~ $PROTECTED_BRANCH ]]; then
+        echo "'$PROTECTED_BRANCH' cannot be deleted!"
+        exit 1
+    fi
     exit 0
 fi
 
